<?php

/*
 * Esse arquivo faz parte de <MasterMundi/Master MDR>
 * (c) Nome Autor zehluiz17[at]gmail.com
 *
 */

use Illuminate\Database\Seeder;

class BancoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('banco')->insert([
            [
                'nome' =>'Banco Bankpar S.A.',
                'codigo' => '000',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' =>'Banco do Brasil S.A.',
                'codigo' => '001',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' =>'Banco da Amazônia S.A.',
                'codigo' => '003',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' =>'Banco do Nordeste do Brasil S.A.',
                'codigo' => '004',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' =>'Banco Standard de Investimentos S.A.',
                'codigo' => '012',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' =>'BANESTES S.A. Banco do Estado do Espírito Santo',
                'codigo' => '021',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco de Pernambuco S.A. - BANDEPE',
                'codigo' => '024',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco Alfa S.A.',
                'codigo' => '025',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco Banerj S.A.',
                'codigo' => '029',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco Beg S.A.',
                'codigo' => '031',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco Santander (Brasil) S.A.',
                'codigo' => '033',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco Bradesco BBI S.A.',
                'codigo' => '036',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco do Estado do Pará S.A.',
                'codigo' => '037',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco Cargill S.A.',
                'codigo' => '040',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco do Estado do Rio Grande do Sul S.A.',
                'codigo' => '041',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco Opportunity S.A.',
                'codigo' => '045',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco do Estado de Sergipe S.A.',
                'codigo' => '047',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Hipercard Banco Múltiplo S.A.',
                'codigo' => '062',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco Ibi S.A. Banco Múltiplo',
                'codigo' => '063',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Goldman Sachs do Brasil Banco Múltiplo S.A.',
                'codigo' => '064',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'Banco Bracce S.A.',
                'codigo' => '065',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'nome' => 'BPN Brasil Banco Múltiplo S.A.',
                'codigo' => '069',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '070',
                'nome' => 'BRB - Banco de Brasília S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '081-7',
                'nome' => 'Concórdia Banco S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '082-5',
                'nome' => 'Banco Topázio S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '083-3',
                'nome' => 'Banco da China Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '072',
                'nome' => 'Banco Rural Mais S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '073',
                'nome' => 'BB Banco Popular do Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '074',
                'nome' => 'Banco J. Safra S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '075',
                'nome' => 'Banco ABN AMRO S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '078',
                'nome' => 'BES Investimento do Brasil S.A. - Banco de Investimento',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '095',
                'nome' => 'Banco Confidence de Câmbio S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '096',
                'nome' => 'Banco BM&FBOVESPA de Serviços de Liquidação e Cust,ódia S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '104',
                'nome' => 'Caixa Econômica Federal',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '107',
                'nome' => 'Banco BBM S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '119',
                'nome' => 'Banco Western Union do Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '125',
                'nome' => 'Brasil Plural S.A. - Banco Múltiplo',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '184',
                'nome' => 'Banco Itaú BBA S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '204',
                'nome' => 'Banco Bradesco Cartões S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '208',
                'nome' => 'Banco BTG Pactual S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '212',
                'nome' => 'Banco Original S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '214',
                'nome' => 'Banco Dibens S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '215',
                'nome' => 'Banco Comercial e de Investimento Sudameris S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '217',
                'nome' => 'Banco John Deere S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '218',
                'nome' => 'Banco Bonsucesso S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '222',
                'nome' => 'Banco Credit Agricole Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '224',
                'nome' => 'Banco Fibra S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '230',
                'nome' => 'Unicard Banco Múltiplo S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '233',
                'nome' => 'Banco Cifra S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '237',
                'nome' => 'Banco Bradesco S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '246',
                'nome' => 'Banco ABC Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '248',
                'nome' => 'Banco Boavista Interatlântico S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '249',
                'nome' => 'Banco Investcred Unibanco S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '250',
                'nome' => 'BCV - Banco de Crédito e Varejo S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '263',
                'nome' => 'Banco Cacique S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '265',
                'nome' => 'Banco Fator S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '318',
                'nome' => 'Banco BMG S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '320',
                'nome' => 'Banco Industrial e Comercial S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '341',
                'nome' => 'Itaú Unibanco S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '356',
                'nome' => 'Banco Real S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '366',
                'nome' => 'Banco Société Générale Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '370',
                'nome' => 'Banco Mizuho do Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '376',
                'nome' => 'Banco J. P. Morgan S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '389',
                'nome' => 'Banco Mercantil do Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '394',
                'nome' => 'Banco Bradesco Financiamentos S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '394',
                'nome' => 'Banco Finasa BMC S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '399',
                'nome' => 'HSBC Bank Brasil S.A. - Banco Múltiplo',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '409',
                'nome' => 'UNIBANCO - União de Bancos Brasileiros S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '422',
                'nome' => 'Banco Safra S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '453',
                'nome' => 'Banco Rural S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '456',
                'nome' => 'Banco de Tokyo-Mitsubishi UFJ Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '464',
                'nome' => 'Banco Sumitomo Mitsui Brasileiro S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '473',
                'nome' => 'Banco Caixa Geral - Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '477',
                'nome' => 'Citibank S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '479',
                'nome' => 'Banco ItaúBank S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '487',
                'nome' => 'Deutsche Bank S.A. - Banco Alemão',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '488',
                'nome' => 'JPMorgan Chase Bank',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '492',
                'nome' => 'ING Bank N.V.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '505',
                'nome' => 'Banco Credit Suisse (Brasil) S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '600',
                'nome' => 'Banco Luso Brasileiro S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '604',
                'nome' => 'Banco Industrial do Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '610',
                'nome' => 'Banco VR S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '611',
                'nome' => 'Banco Paulista S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '612',
                'nome' => 'Banco Guanabara S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '623',
                'nome' => 'Banco Panamericano S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '626',
                'nome' => 'Banco Ficsa S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '633',
                'nome' => 'Banco Rendimento S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '634',
                'nome' => 'Banco Triângulo S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '641',
                'nome' => 'Banco Alvorada S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '643',
                'nome' => 'Banco Pine S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '652',
                'nome' => 'Itaú Unibanco Holding S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '653',
                'nome' => 'Banco Indusval S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '655',
                'nome' => 'Banco Votorantim S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '707',
                'nome' => 'Banco Daycoval S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '719',
                'nome' => 'Banif-Banco Internacional do Funchal (Brasil)S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '739',
                'nome' => 'Banco BGN S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '740',
                'nome' => 'Banco Barclays S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '745',
                'nome' => 'Banco Citibank S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '746',
                'nome' => 'Banco Modal S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '747',
                'nome' => 'Banco Rabobank International Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '748',
                'nome' => 'Banco Cooperativo Sicredi S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '749',
                'nome' => 'Banco Simples S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '751',
                'nome' => 'Scotiabank Brasil S.A. Banco Múltiplo',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '752',
                'nome' => 'Banco BNP Paribas Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '755',
                'nome' => 'Bank of America Merrill Lynch Banco Múltiplo S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => '756',
                'nome' => 'Banco Cooperativo do Brasil S.A. - BANCOOB / SICOOB',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M03',
                'nome' => 'Banco Fiat S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M06',
                'nome' => 'Banco de Lage Landen Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M07',
                'nome' => 'Banco GMAC S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M08',
                'nome' => 'Banco Citicard S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M09',
                'nome' => 'Banco Itaucred Financiamentos S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M11',
                'nome' => 'Banco IBM S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M14',
                'nome' => 'Banco Volkswagen S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M16',
                'nome' => 'Banco Rodobens S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M18',
                'nome' => 'Banco Ford S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M19',
                'nome' => 'Banco CNH Capital S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M20',
                'nome' => 'Banco Toyota do Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M22',
                'nome' => 'Banco Honda S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M23',
                'nome' => 'Banco Volvo (Brasil) S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ], [
                'codigo' => 'M24',
                'nome' => 'Banco PSA Finance Brasil S.A.',
                'class_cor' => 'warning',
                'created_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Carbon\Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
